#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_SuperLiga
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Superliga")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertEquipa(Equipa instance);
    partial void UpdateEquipa(Equipa instance);
    partial void DeleteEquipa(Equipa instance);
    partial void InsertImagen(Imagen instance);
    partial void UpdateImagen(Imagen instance);
    partial void DeleteImagen(Imagen instance);
    partial void InsertJogadore(Jogadore instance);
    partial void UpdateJogadore(Jogadore instance);
    partial void DeleteJogadore(Jogadore instance);
    partial void InsertStaff(Staff instance);
    partial void UpdateStaff(Staff instance);
    partial void DeleteStaff(Staff instance);
    partial void InsertJornada(Jornada instance);
    partial void UpdateJornada(Jornada instance);
    partial void DeleteJornada(Jornada instance);
    partial void InsertJogo(Jogo instance);
    partial void UpdateJogo(Jogo instance);
    partial void DeleteJogo(Jogo instance);
    partial void InsertResultado(Resultado instance);
    partial void UpdateResultado(Resultado instance);
    partial void DeleteResultado(Resultado instance);
    partial void InsertEstatistica(Estatistica instance);
    partial void UpdateEstatistica(Estatistica instance);
    partial void DeleteEstatistica(Estatistica instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::App_SuperLiga.Properties.Settings.Default.SuperligaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Equipa> Equipas
		{
			get
			{
				return this.GetTable<Equipa>();
			}
		}
		
		public System.Data.Linq.Table<Imagen> Imagens
		{
			get
			{
				return this.GetTable<Imagen>();
			}
		}
		
		public System.Data.Linq.Table<Jogadore> Jogadores
		{
			get
			{
				return this.GetTable<Jogadore>();
			}
		}
		
		public System.Data.Linq.Table<Staff> Staffs
		{
			get
			{
				return this.GetTable<Staff>();
			}
		}
		
		public System.Data.Linq.Table<Jornada> Jornadas
		{
			get
			{
				return this.GetTable<Jornada>();
			}
		}
		
		public System.Data.Linq.Table<Jogo> Jogos
		{
			get
			{
				return this.GetTable<Jogo>();
			}
		}
		
		public System.Data.Linq.Table<Resultado> Resultados
		{
			get
			{
				return this.GetTable<Resultado>();
			}
		}
		
		public System.Data.Linq.Table<Estatistica> Estatisticas
		{
			get
			{
				return this.GetTable<Estatistica>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Equipas")]
	public partial class Equipa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_equipa;
		
		private string _nome;
		
		private string _estadio;
		
		private EntitySet<Imagen> _Imagens;
		
		private EntitySet<Jogadore> _Jogadores;
		
		private EntitySet<Staff> _Staffs;
		
		private EntitySet<Jogo> _Jogos;
		
		private EntitySet<Jogo> _Jogos1;
		
		private EntitySet<Estatistica> _Estatisticas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_equipaChanging(int value);
    partial void Onid_equipaChanged();
    partial void OnnomeChanging(string value);
    partial void OnnomeChanged();
    partial void OnestadioChanging(string value);
    partial void OnestadioChanged();
    #endregion
		
		public Equipa()
		{
			this._Imagens = new EntitySet<Imagen>(new Action<Imagen>(this.attach_Imagens), new Action<Imagen>(this.detach_Imagens));
			this._Jogadores = new EntitySet<Jogadore>(new Action<Jogadore>(this.attach_Jogadores), new Action<Jogadore>(this.detach_Jogadores));
			this._Staffs = new EntitySet<Staff>(new Action<Staff>(this.attach_Staffs), new Action<Staff>(this.detach_Staffs));
			this._Jogos = new EntitySet<Jogo>(new Action<Jogo>(this.attach_Jogos), new Action<Jogo>(this.detach_Jogos));
			this._Jogos1 = new EntitySet<Jogo>(new Action<Jogo>(this.attach_Jogos1), new Action<Jogo>(this.detach_Jogos1));
			this._Estatisticas = new EntitySet<Estatistica>(new Action<Estatistica>(this.attach_Estatisticas), new Action<Estatistica>(this.detach_Estatisticas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_equipa", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_equipa
		{
			get
			{
				return this._id_equipa;
			}
			set
			{
				if ((this._id_equipa != value))
				{
					this.Onid_equipaChanging(value);
					this.SendPropertyChanging();
					this._id_equipa = value;
					this.SendPropertyChanged("id_equipa");
					this.Onid_equipaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nome", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nome
		{
			get
			{
				return this._nome;
			}
			set
			{
				if ((this._nome != value))
				{
					this.OnnomeChanging(value);
					this.SendPropertyChanging();
					this._nome = value;
					this.SendPropertyChanged("nome");
					this.OnnomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estadio", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string estadio
		{
			get
			{
				return this._estadio;
			}
			set
			{
				if ((this._estadio != value))
				{
					this.OnestadioChanging(value);
					this.SendPropertyChanging();
					this._estadio = value;
					this.SendPropertyChanged("estadio");
					this.OnestadioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Equipa_Imagen", Storage="_Imagens", ThisKey="id_equipa", OtherKey="id_equipa")]
		public EntitySet<Imagen> Imagens
		{
			get
			{
				return this._Imagens;
			}
			set
			{
				this._Imagens.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Equipa_Jogadore", Storage="_Jogadores", ThisKey="id_equipa", OtherKey="id_equipa")]
		public EntitySet<Jogadore> Jogadores
		{
			get
			{
				return this._Jogadores;
			}
			set
			{
				this._Jogadores.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Equipa_Staff", Storage="_Staffs", ThisKey="id_equipa", OtherKey="id_equipa")]
		public EntitySet<Staff> Staffs
		{
			get
			{
				return this._Staffs;
			}
			set
			{
				this._Staffs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Equipa_Jogo", Storage="_Jogos", ThisKey="id_equipa", OtherKey="equipa_casa")]
		public EntitySet<Jogo> Jogos
		{
			get
			{
				return this._Jogos;
			}
			set
			{
				this._Jogos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Equipa_Jogo1", Storage="_Jogos1", ThisKey="id_equipa", OtherKey="equipa_fora")]
		public EntitySet<Jogo> Jogos1
		{
			get
			{
				return this._Jogos1;
			}
			set
			{
				this._Jogos1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Equipa_Estatistica", Storage="_Estatisticas", ThisKey="id_equipa", OtherKey="id_equipa")]
		public EntitySet<Estatistica> Estatisticas
		{
			get
			{
				return this._Estatisticas;
			}
			set
			{
				this._Estatisticas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Imagens(Imagen entity)
		{
			this.SendPropertyChanging();
			entity.Equipa = this;
		}
		
		private void detach_Imagens(Imagen entity)
		{
			this.SendPropertyChanging();
			entity.Equipa = null;
		}
		
		private void attach_Jogadores(Jogadore entity)
		{
			this.SendPropertyChanging();
			entity.Equipa = this;
		}
		
		private void detach_Jogadores(Jogadore entity)
		{
			this.SendPropertyChanging();
			entity.Equipa = null;
		}
		
		private void attach_Staffs(Staff entity)
		{
			this.SendPropertyChanging();
			entity.Equipa = this;
		}
		
		private void detach_Staffs(Staff entity)
		{
			this.SendPropertyChanging();
			entity.Equipa = null;
		}
		
		private void attach_Jogos(Jogo entity)
		{
			this.SendPropertyChanging();
			entity.Equipa = this;
		}
		
		private void detach_Jogos(Jogo entity)
		{
			this.SendPropertyChanging();
			entity.Equipa = null;
		}
		
		private void attach_Jogos1(Jogo entity)
		{
			this.SendPropertyChanging();
			entity.Equipa1 = this;
		}
		
		private void detach_Jogos1(Jogo entity)
		{
			this.SendPropertyChanging();
			entity.Equipa1 = null;
		}
		
		private void attach_Estatisticas(Estatistica entity)
		{
			this.SendPropertyChanging();
			entity.Equipa = this;
		}
		
		private void detach_Estatisticas(Estatistica entity)
		{
			this.SendPropertyChanging();
			entity.Equipa = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Imagens")]
	public partial class Imagen : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_imagem;
		
		private System.Data.Linq.Binary _imagem;
		
		private int _id_equipa;
		
		private EntityRef<Equipa> _Equipa;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_imagemChanging(int value);
    partial void Onid_imagemChanged();
    partial void OnimagemChanging(System.Data.Linq.Binary value);
    partial void OnimagemChanged();
    partial void Onid_equipaChanging(int value);
    partial void Onid_equipaChanged();
    #endregion
		
		public Imagen()
		{
			this._Equipa = default(EntityRef<Equipa>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_imagem", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_imagem
		{
			get
			{
				return this._id_imagem;
			}
			set
			{
				if ((this._id_imagem != value))
				{
					this.Onid_imagemChanging(value);
					this.SendPropertyChanging();
					this._id_imagem = value;
					this.SendPropertyChanged("id_imagem");
					this.Onid_imagemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imagem", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary imagem
		{
			get
			{
				return this._imagem;
			}
			set
			{
				if ((this._imagem != value))
				{
					this.OnimagemChanging(value);
					this.SendPropertyChanging();
					this._imagem = value;
					this.SendPropertyChanged("imagem");
					this.OnimagemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_equipa", DbType="Int NOT NULL")]
		public int id_equipa
		{
			get
			{
				return this._id_equipa;
			}
			set
			{
				if ((this._id_equipa != value))
				{
					if (this._Equipa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_equipaChanging(value);
					this.SendPropertyChanging();
					this._id_equipa = value;
					this.SendPropertyChanged("id_equipa");
					this.Onid_equipaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Equipa_Imagen", Storage="_Equipa", ThisKey="id_equipa", OtherKey="id_equipa", IsForeignKey=true)]
		public Equipa Equipa
		{
			get
			{
				return this._Equipa.Entity;
			}
			set
			{
				Equipa previousValue = this._Equipa.Entity;
				if (((previousValue != value) 
							|| (this._Equipa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Equipa.Entity = null;
						previousValue.Imagens.Remove(this);
					}
					this._Equipa.Entity = value;
					if ((value != null))
					{
						value.Imagens.Add(this);
						this._id_equipa = value.id_equipa;
					}
					else
					{
						this._id_equipa = default(int);
					}
					this.SendPropertyChanged("Equipa");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Jogadores")]
	public partial class Jogadore : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_jogador;
		
		private string _nome;
		
		private string _posicao;
		
		private int _numero;
		
		private int _id_equipa;
		
		private EntityRef<Equipa> _Equipa;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_jogadorChanging(int value);
    partial void Onid_jogadorChanged();
    partial void OnnomeChanging(string value);
    partial void OnnomeChanged();
    partial void OnposicaoChanging(string value);
    partial void OnposicaoChanged();
    partial void OnnumeroChanging(int value);
    partial void OnnumeroChanged();
    partial void Onid_equipaChanging(int value);
    partial void Onid_equipaChanged();
    #endregion
		
		public Jogadore()
		{
			this._Equipa = default(EntityRef<Equipa>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_jogador", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_jogador
		{
			get
			{
				return this._id_jogador;
			}
			set
			{
				if ((this._id_jogador != value))
				{
					this.Onid_jogadorChanging(value);
					this.SendPropertyChanging();
					this._id_jogador = value;
					this.SendPropertyChanged("id_jogador");
					this.Onid_jogadorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nome", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nome
		{
			get
			{
				return this._nome;
			}
			set
			{
				if ((this._nome != value))
				{
					this.OnnomeChanging(value);
					this.SendPropertyChanging();
					this._nome = value;
					this.SendPropertyChanged("nome");
					this.OnnomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_posicao", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string posicao
		{
			get
			{
				return this._posicao;
			}
			set
			{
				if ((this._posicao != value))
				{
					this.OnposicaoChanging(value);
					this.SendPropertyChanging();
					this._posicao = value;
					this.SendPropertyChanged("posicao");
					this.OnposicaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numero", DbType="Int NOT NULL")]
		public int numero
		{
			get
			{
				return this._numero;
			}
			set
			{
				if ((this._numero != value))
				{
					this.OnnumeroChanging(value);
					this.SendPropertyChanging();
					this._numero = value;
					this.SendPropertyChanged("numero");
					this.OnnumeroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_equipa", DbType="Int NOT NULL")]
		public int id_equipa
		{
			get
			{
				return this._id_equipa;
			}
			set
			{
				if ((this._id_equipa != value))
				{
					if (this._Equipa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_equipaChanging(value);
					this.SendPropertyChanging();
					this._id_equipa = value;
					this.SendPropertyChanged("id_equipa");
					this.Onid_equipaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Equipa_Jogadore", Storage="_Equipa", ThisKey="id_equipa", OtherKey="id_equipa", IsForeignKey=true)]
		public Equipa Equipa
		{
			get
			{
				return this._Equipa.Entity;
			}
			set
			{
				Equipa previousValue = this._Equipa.Entity;
				if (((previousValue != value) 
							|| (this._Equipa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Equipa.Entity = null;
						previousValue.Jogadores.Remove(this);
					}
					this._Equipa.Entity = value;
					if ((value != null))
					{
						value.Jogadores.Add(this);
						this._id_equipa = value.id_equipa;
					}
					else
					{
						this._id_equipa = default(int);
					}
					this.SendPropertyChanged("Equipa");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Staff")]
	public partial class Staff : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_staff;
		
		private string _nome;
		
		private string _funcao;
		
		private int _id_equipa;
		
		private EntityRef<Equipa> _Equipa;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_staffChanging(int value);
    partial void Onid_staffChanged();
    partial void OnnomeChanging(string value);
    partial void OnnomeChanged();
    partial void OnfuncaoChanging(string value);
    partial void OnfuncaoChanged();
    partial void Onid_equipaChanging(int value);
    partial void Onid_equipaChanged();
    #endregion
		
		public Staff()
		{
			this._Equipa = default(EntityRef<Equipa>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_staff", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_staff
		{
			get
			{
				return this._id_staff;
			}
			set
			{
				if ((this._id_staff != value))
				{
					this.Onid_staffChanging(value);
					this.SendPropertyChanging();
					this._id_staff = value;
					this.SendPropertyChanged("id_staff");
					this.Onid_staffChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nome", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nome
		{
			get
			{
				return this._nome;
			}
			set
			{
				if ((this._nome != value))
				{
					this.OnnomeChanging(value);
					this.SendPropertyChanging();
					this._nome = value;
					this.SendPropertyChanged("nome");
					this.OnnomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_funcao", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string funcao
		{
			get
			{
				return this._funcao;
			}
			set
			{
				if ((this._funcao != value))
				{
					this.OnfuncaoChanging(value);
					this.SendPropertyChanging();
					this._funcao = value;
					this.SendPropertyChanged("funcao");
					this.OnfuncaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_equipa", DbType="Int NOT NULL")]
		public int id_equipa
		{
			get
			{
				return this._id_equipa;
			}
			set
			{
				if ((this._id_equipa != value))
				{
					if (this._Equipa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_equipaChanging(value);
					this.SendPropertyChanging();
					this._id_equipa = value;
					this.SendPropertyChanged("id_equipa");
					this.Onid_equipaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Equipa_Staff", Storage="_Equipa", ThisKey="id_equipa", OtherKey="id_equipa", IsForeignKey=true)]
		public Equipa Equipa
		{
			get
			{
				return this._Equipa.Entity;
			}
			set
			{
				Equipa previousValue = this._Equipa.Entity;
				if (((previousValue != value) 
							|| (this._Equipa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Equipa.Entity = null;
						previousValue.Staffs.Remove(this);
					}
					this._Equipa.Entity = value;
					if ((value != null))
					{
						value.Staffs.Add(this);
						this._id_equipa = value.id_equipa;
					}
					else
					{
						this._id_equipa = default(int);
					}
					this.SendPropertyChanged("Equipa");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Jornadas")]
	public partial class Jornada : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_jornada;
		
		private string _descricao;
		
		private EntitySet<Jogo> _Jogos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_jornadaChanging(int value);
    partial void Onid_jornadaChanged();
    partial void OndescricaoChanging(string value);
    partial void OndescricaoChanged();
    #endregion
		
		public Jornada()
		{
			this._Jogos = new EntitySet<Jogo>(new Action<Jogo>(this.attach_Jogos), new Action<Jogo>(this.detach_Jogos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_jornada", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_jornada
		{
			get
			{
				return this._id_jornada;
			}
			set
			{
				if ((this._id_jornada != value))
				{
					this.Onid_jornadaChanging(value);
					this.SendPropertyChanging();
					this._id_jornada = value;
					this.SendPropertyChanged("id_jornada");
					this.Onid_jornadaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descricao", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string descricao
		{
			get
			{
				return this._descricao;
			}
			set
			{
				if ((this._descricao != value))
				{
					this.OndescricaoChanging(value);
					this.SendPropertyChanging();
					this._descricao = value;
					this.SendPropertyChanged("descricao");
					this.OndescricaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Jornada_Jogo", Storage="_Jogos", ThisKey="id_jornada", OtherKey="id_jornada")]
		public EntitySet<Jogo> Jogos
		{
			get
			{
				return this._Jogos;
			}
			set
			{
				this._Jogos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Jogos(Jogo entity)
		{
			this.SendPropertyChanging();
			entity.Jornada = this;
		}
		
		private void detach_Jogos(Jogo entity)
		{
			this.SendPropertyChanging();
			entity.Jornada = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Jogos")]
	public partial class Jogo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_jogo;
		
		private int _equipa_casa;
		
		private int _equipa_fora;
		
		private int _id_jornada;
		
		private System.Nullable<System.DateTime> _data_jogo;
		
		private EntitySet<Resultado> _Resultados;
		
		private EntityRef<Equipa> _Equipa;
		
		private EntityRef<Equipa> _Equipa1;
		
		private EntityRef<Jornada> _Jornada;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_jogoChanging(int value);
    partial void Onid_jogoChanged();
    partial void Onequipa_casaChanging(int value);
    partial void Onequipa_casaChanged();
    partial void Onequipa_foraChanging(int value);
    partial void Onequipa_foraChanged();
    partial void Onid_jornadaChanging(int value);
    partial void Onid_jornadaChanged();
    partial void Ondata_jogoChanging(System.Nullable<System.DateTime> value);
    partial void Ondata_jogoChanged();
    #endregion
		
		public Jogo()
		{
			this._Resultados = new EntitySet<Resultado>(new Action<Resultado>(this.attach_Resultados), new Action<Resultado>(this.detach_Resultados));
			this._Equipa = default(EntityRef<Equipa>);
			this._Equipa1 = default(EntityRef<Equipa>);
			this._Jornada = default(EntityRef<Jornada>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_jogo", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_jogo
		{
			get
			{
				return this._id_jogo;
			}
			set
			{
				if ((this._id_jogo != value))
				{
					this.Onid_jogoChanging(value);
					this.SendPropertyChanging();
					this._id_jogo = value;
					this.SendPropertyChanged("id_jogo");
					this.Onid_jogoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_equipa_casa", DbType="Int NOT NULL")]
		public int equipa_casa
		{
			get
			{
				return this._equipa_casa;
			}
			set
			{
				if ((this._equipa_casa != value))
				{
					if (this._Equipa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onequipa_casaChanging(value);
					this.SendPropertyChanging();
					this._equipa_casa = value;
					this.SendPropertyChanged("equipa_casa");
					this.Onequipa_casaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_equipa_fora", DbType="Int NOT NULL")]
		public int equipa_fora
		{
			get
			{
				return this._equipa_fora;
			}
			set
			{
				if ((this._equipa_fora != value))
				{
					if (this._Equipa1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onequipa_foraChanging(value);
					this.SendPropertyChanging();
					this._equipa_fora = value;
					this.SendPropertyChanged("equipa_fora");
					this.Onequipa_foraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_jornada", DbType="Int NOT NULL")]
		public int id_jornada
		{
			get
			{
				return this._id_jornada;
			}
			set
			{
				if ((this._id_jornada != value))
				{
					if (this._Jornada.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_jornadaChanging(value);
					this.SendPropertyChanging();
					this._id_jornada = value;
					this.SendPropertyChanged("id_jornada");
					this.Onid_jornadaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_jogo", DbType="Date")]
		public System.Nullable<System.DateTime> data_jogo
		{
			get
			{
				return this._data_jogo;
			}
			set
			{
				if ((this._data_jogo != value))
				{
					this.Ondata_jogoChanging(value);
					this.SendPropertyChanging();
					this._data_jogo = value;
					this.SendPropertyChanged("data_jogo");
					this.Ondata_jogoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Jogo_Resultado", Storage="_Resultados", ThisKey="id_jogo", OtherKey="id_jogo")]
		public EntitySet<Resultado> Resultados
		{
			get
			{
				return this._Resultados;
			}
			set
			{
				this._Resultados.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Equipa_Jogo", Storage="_Equipa", ThisKey="equipa_casa", OtherKey="id_equipa", IsForeignKey=true)]
		public Equipa Equipa
		{
			get
			{
				return this._Equipa.Entity;
			}
			set
			{
				Equipa previousValue = this._Equipa.Entity;
				if (((previousValue != value) 
							|| (this._Equipa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Equipa.Entity = null;
						previousValue.Jogos.Remove(this);
					}
					this._Equipa.Entity = value;
					if ((value != null))
					{
						value.Jogos.Add(this);
						this._equipa_casa = value.id_equipa;
					}
					else
					{
						this._equipa_casa = default(int);
					}
					this.SendPropertyChanged("Equipa");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Equipa_Jogo1", Storage="_Equipa1", ThisKey="equipa_fora", OtherKey="id_equipa", IsForeignKey=true)]
		public Equipa Equipa1
		{
			get
			{
				return this._Equipa1.Entity;
			}
			set
			{
				Equipa previousValue = this._Equipa1.Entity;
				if (((previousValue != value) 
							|| (this._Equipa1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Equipa1.Entity = null;
						previousValue.Jogos1.Remove(this);
					}
					this._Equipa1.Entity = value;
					if ((value != null))
					{
						value.Jogos1.Add(this);
						this._equipa_fora = value.id_equipa;
					}
					else
					{
						this._equipa_fora = default(int);
					}
					this.SendPropertyChanged("Equipa1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Jornada_Jogo", Storage="_Jornada", ThisKey="id_jornada", OtherKey="id_jornada", IsForeignKey=true)]
		public Jornada Jornada
		{
			get
			{
				return this._Jornada.Entity;
			}
			set
			{
				Jornada previousValue = this._Jornada.Entity;
				if (((previousValue != value) 
							|| (this._Jornada.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Jornada.Entity = null;
						previousValue.Jogos.Remove(this);
					}
					this._Jornada.Entity = value;
					if ((value != null))
					{
						value.Jogos.Add(this);
						this._id_jornada = value.id_jornada;
					}
					else
					{
						this._id_jornada = default(int);
					}
					this.SendPropertyChanged("Jornada");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Resultados(Resultado entity)
		{
			this.SendPropertyChanging();
			entity.Jogo = this;
		}
		
		private void detach_Resultados(Resultado entity)
		{
			this.SendPropertyChanging();
			entity.Jogo = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Resultados")]
	public partial class Resultado : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_resultado;
		
		private int _id_jogo;
		
		private int _id_jornada;
		
		private int _golos_casa;
		
		private int _golos_fora;
		
		private System.Nullable<int> _equipa_casa;
		
		private System.Nullable<int> _equipa_fora;
		
		private EntityRef<Jogo> _Jogo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_resultadoChanging(int value);
    partial void Onid_resultadoChanged();
    partial void Onid_jogoChanging(int value);
    partial void Onid_jogoChanged();
    partial void Onid_jornadaChanging(int value);
    partial void Onid_jornadaChanged();
    partial void Ongolos_casaChanging(int value);
    partial void Ongolos_casaChanged();
    partial void Ongolos_foraChanging(int value);
    partial void Ongolos_foraChanged();
    partial void Onequipa_casaChanging(System.Nullable<int> value);
    partial void Onequipa_casaChanged();
    partial void Onequipa_foraChanging(System.Nullable<int> value);
    partial void Onequipa_foraChanged();
    #endregion
		
		public Resultado()
		{
			this._Jogo = default(EntityRef<Jogo>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_resultado", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_resultado
		{
			get
			{
				return this._id_resultado;
			}
			set
			{
				if ((this._id_resultado != value))
				{
					this.Onid_resultadoChanging(value);
					this.SendPropertyChanging();
					this._id_resultado = value;
					this.SendPropertyChanged("id_resultado");
					this.Onid_resultadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_jogo", DbType="Int NOT NULL")]
		public int id_jogo
		{
			get
			{
				return this._id_jogo;
			}
			set
			{
				if ((this._id_jogo != value))
				{
					if (this._Jogo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_jogoChanging(value);
					this.SendPropertyChanging();
					this._id_jogo = value;
					this.SendPropertyChanged("id_jogo");
					this.Onid_jogoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_jornada", DbType="Int NOT NULL")]
		public int id_jornada
		{
			get
			{
				return this._id_jornada;
			}
			set
			{
				if ((this._id_jornada != value))
				{
					this.Onid_jornadaChanging(value);
					this.SendPropertyChanging();
					this._id_jornada = value;
					this.SendPropertyChanged("id_jornada");
					this.Onid_jornadaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_golos_casa", DbType="Int NOT NULL")]
		public int golos_casa
		{
			get
			{
				return this._golos_casa;
			}
			set
			{
				if ((this._golos_casa != value))
				{
					this.Ongolos_casaChanging(value);
					this.SendPropertyChanging();
					this._golos_casa = value;
					this.SendPropertyChanged("golos_casa");
					this.Ongolos_casaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_golos_fora", DbType="Int NOT NULL")]
		public int golos_fora
		{
			get
			{
				return this._golos_fora;
			}
			set
			{
				if ((this._golos_fora != value))
				{
					this.Ongolos_foraChanging(value);
					this.SendPropertyChanging();
					this._golos_fora = value;
					this.SendPropertyChanged("golos_fora");
					this.Ongolos_foraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_equipa_casa", DbType="Int")]
		public System.Nullable<int> equipa_casa
		{
			get
			{
				return this._equipa_casa;
			}
			set
			{
				if ((this._equipa_casa != value))
				{
					this.Onequipa_casaChanging(value);
					this.SendPropertyChanging();
					this._equipa_casa = value;
					this.SendPropertyChanged("equipa_casa");
					this.Onequipa_casaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_equipa_fora", DbType="Int")]
		public System.Nullable<int> equipa_fora
		{
			get
			{
				return this._equipa_fora;
			}
			set
			{
				if ((this._equipa_fora != value))
				{
					this.Onequipa_foraChanging(value);
					this.SendPropertyChanging();
					this._equipa_fora = value;
					this.SendPropertyChanged("equipa_fora");
					this.Onequipa_foraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Jogo_Resultado", Storage="_Jogo", ThisKey="id_jogo", OtherKey="id_jogo", IsForeignKey=true)]
		public Jogo Jogo
		{
			get
			{
				return this._Jogo.Entity;
			}
			set
			{
				Jogo previousValue = this._Jogo.Entity;
				if (((previousValue != value) 
							|| (this._Jogo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Jogo.Entity = null;
						previousValue.Resultados.Remove(this);
					}
					this._Jogo.Entity = value;
					if ((value != null))
					{
						value.Resultados.Add(this);
						this._id_jogo = value.id_jogo;
					}
					else
					{
						this._id_jogo = default(int);
					}
					this.SendPropertyChanged("Jogo");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Estatisticas")]
	public partial class Estatistica : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_estatistica;
		
		private int _id_equipa;
		
		private System.Nullable<int> _vitorias;
		
		private System.Nullable<int> _empates;
		
		private System.Nullable<int> _derrotas;
		
		private System.Nullable<int> _pontos;
		
		private System.Nullable<int> _golos_marcados;
		
		private System.Nullable<int> _golos_sofridos;
		
		private System.Nullable<int> _total_jogos;
		
		private string _nome_equipa;
		
		private System.Data.Linq.Binary _imagem_equipa;
		
		private EntityRef<Equipa> _Equipa;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_estatisticaChanging(int value);
    partial void Onid_estatisticaChanged();
    partial void Onid_equipaChanging(int value);
    partial void Onid_equipaChanged();
    partial void OnvitoriasChanging(System.Nullable<int> value);
    partial void OnvitoriasChanged();
    partial void OnempatesChanging(System.Nullable<int> value);
    partial void OnempatesChanged();
    partial void OnderrotasChanging(System.Nullable<int> value);
    partial void OnderrotasChanged();
    partial void OnpontosChanging(System.Nullable<int> value);
    partial void OnpontosChanged();
    partial void Ongolos_marcadosChanging(System.Nullable<int> value);
    partial void Ongolos_marcadosChanged();
    partial void Ongolos_sofridosChanging(System.Nullable<int> value);
    partial void Ongolos_sofridosChanged();
    partial void Ontotal_jogosChanging(System.Nullable<int> value);
    partial void Ontotal_jogosChanged();
    partial void Onnome_equipaChanging(string value);
    partial void Onnome_equipaChanged();
    partial void Onimagem_equipaChanging(System.Data.Linq.Binary value);
    partial void Onimagem_equipaChanged();
    #endregion
		
		public Estatistica()
		{
			this._Equipa = default(EntityRef<Equipa>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_estatistica", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_estatistica
		{
			get
			{
				return this._id_estatistica;
			}
			set
			{
				if ((this._id_estatistica != value))
				{
					this.Onid_estatisticaChanging(value);
					this.SendPropertyChanging();
					this._id_estatistica = value;
					this.SendPropertyChanged("id_estatistica");
					this.Onid_estatisticaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_equipa", DbType="Int NOT NULL")]
		public int id_equipa
		{
			get
			{
				return this._id_equipa;
			}
			set
			{
				if ((this._id_equipa != value))
				{
					if (this._Equipa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_equipaChanging(value);
					this.SendPropertyChanging();
					this._id_equipa = value;
					this.SendPropertyChanged("id_equipa");
					this.Onid_equipaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vitorias", DbType="Int")]
		public System.Nullable<int> vitorias
		{
			get
			{
				return this._vitorias;
			}
			set
			{
				if ((this._vitorias != value))
				{
					this.OnvitoriasChanging(value);
					this.SendPropertyChanging();
					this._vitorias = value;
					this.SendPropertyChanged("vitorias");
					this.OnvitoriasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_empates", DbType="Int")]
		public System.Nullable<int> empates
		{
			get
			{
				return this._empates;
			}
			set
			{
				if ((this._empates != value))
				{
					this.OnempatesChanging(value);
					this.SendPropertyChanging();
					this._empates = value;
					this.SendPropertyChanged("empates");
					this.OnempatesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_derrotas", DbType="Int")]
		public System.Nullable<int> derrotas
		{
			get
			{
				return this._derrotas;
			}
			set
			{
				if ((this._derrotas != value))
				{
					this.OnderrotasChanging(value);
					this.SendPropertyChanging();
					this._derrotas = value;
					this.SendPropertyChanged("derrotas");
					this.OnderrotasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pontos", DbType="Int")]
		public System.Nullable<int> pontos
		{
			get
			{
				return this._pontos;
			}
			set
			{
				if ((this._pontos != value))
				{
					this.OnpontosChanging(value);
					this.SendPropertyChanging();
					this._pontos = value;
					this.SendPropertyChanged("pontos");
					this.OnpontosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_golos_marcados", DbType="Int")]
		public System.Nullable<int> golos_marcados
		{
			get
			{
				return this._golos_marcados;
			}
			set
			{
				if ((this._golos_marcados != value))
				{
					this.Ongolos_marcadosChanging(value);
					this.SendPropertyChanging();
					this._golos_marcados = value;
					this.SendPropertyChanged("golos_marcados");
					this.Ongolos_marcadosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_golos_sofridos", DbType="Int")]
		public System.Nullable<int> golos_sofridos
		{
			get
			{
				return this._golos_sofridos;
			}
			set
			{
				if ((this._golos_sofridos != value))
				{
					this.Ongolos_sofridosChanging(value);
					this.SendPropertyChanging();
					this._golos_sofridos = value;
					this.SendPropertyChanged("golos_sofridos");
					this.Ongolos_sofridosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total_jogos", DbType="Int")]
		public System.Nullable<int> total_jogos
		{
			get
			{
				return this._total_jogos;
			}
			set
			{
				if ((this._total_jogos != value))
				{
					this.Ontotal_jogosChanging(value);
					this.SendPropertyChanging();
					this._total_jogos = value;
					this.SendPropertyChanged("total_jogos");
					this.Ontotal_jogosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nome_equipa", DbType="VarChar(50)")]
		public string nome_equipa
		{
			get
			{
				return this._nome_equipa;
			}
			set
			{
				if ((this._nome_equipa != value))
				{
					this.Onnome_equipaChanging(value);
					this.SendPropertyChanging();
					this._nome_equipa = value;
					this.SendPropertyChanged("nome_equipa");
					this.Onnome_equipaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imagem_equipa", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary imagem_equipa
		{
			get
			{
				return this._imagem_equipa;
			}
			set
			{
				if ((this._imagem_equipa != value))
				{
					this.Onimagem_equipaChanging(value);
					this.SendPropertyChanging();
					this._imagem_equipa = value;
					this.SendPropertyChanged("imagem_equipa");
					this.Onimagem_equipaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Equipa_Estatistica", Storage="_Equipa", ThisKey="id_equipa", OtherKey="id_equipa", IsForeignKey=true)]
		public Equipa Equipa
		{
			get
			{
				return this._Equipa.Entity;
			}
			set
			{
				Equipa previousValue = this._Equipa.Entity;
				if (((previousValue != value) 
							|| (this._Equipa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Equipa.Entity = null;
						previousValue.Estatisticas.Remove(this);
					}
					this._Equipa.Entity = value;
					if ((value != null))
					{
						value.Estatisticas.Add(this);
						this._id_equipa = value.id_equipa;
					}
					else
					{
						this._id_equipa = default(int);
					}
					this.SendPropertyChanged("Equipa");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
